services:
  - type: worker
    name: saldo-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_slots_flow.py

    envVars:
      # Impostale dal pannello di Render (non nel file):
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      # Consigliato se usi il disco montato (vedi sezione "disk"):
      - key: DB_PATH
        value: /var/data/kwh_slots.db

    disk:
      name: bot-data
      mountPath: /var/data
      sizeGB: 1
